### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by oswal8** [JohannesMilke/google_signin_ii_example#1]
I subscribed to the newsletter and the link of the code of your repository is down, I hope you will solve it soon.

**Comment by aasmoth** [comment]
Same problem

**Comment by JohannesMilke** [comment]
The source code is available. Simply learn more about it here: https://github.com/JohannesMilke/sponsorware#2-why-didnt-i-get-an-email-even-if-i-have-sent-already-a-request-on-your-website
